name: Docs Bumped

on:
  push:
    paths:
      - 'docs/**'
  pull_request:
    paths:
      - 'docs/**'

jobs:
  docs_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Add additional steps here to process docs changes
      - name: Print changed docs files
        run: |
          echo "A change in the docs directory was detected."

      - name: Prepare to trigger slurp_branches workflow in metabase/docs.metabase.github.io
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "BRANCH_NAME=${{ github.head_ref }}" >> $GITHUB_ENV
          else
            echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          fi

      # Trigger the repository_dispatch event in the target repo
      - name: Trigger Workflow in `metabase/docs.metabase.github.io`
        env:
          TOKEN: ${{ secrets.METABASE_AUTOMATION_USER_TOKEN }}
        run: |
          echo $BRANCH_NAME
          echo "Triggering workflow in metabase/docs.metabase.github.io with branch: $BRANCH_NAME"
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${TOKEN}" \
            https://api.github.com/repos/metabase/docs.metabase.github.io/slurp_branches/dispatches \
            -d "{\"event_type\": \"trigger-workflow\", \"client_payload\": {\"branch\": \"$BRANCH_NAME\"}}"
