name: E2E Matrix Builder

on:
  workflow_call:
    inputs:
      chunks:
        required: true
        type: number
        default: 30
      specs:
        required: false
        type: string
        default: "./e2e/test/scenarios/**/*.cy.spec.*"
    outputs:
      matrix:
        value: ${{ jobs.build-matrix.outputs.matrix }}
      regularChunks:
        value: ${{ jobs.build-matrix.outputs.regularChunks }}

jobs:
  build-matrix:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    outputs:
      matrix: ${{ steps.matrix.outputs.config }}
      regularChunks: ${{ steps.matrix.outputs.regularChunks }}
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: lts/Jod # 22.x.x
      - uses: actions/github-script@v7
        id: matrix
        env:
          chunks: ${{ inputs.chunks }}
        with:
          script: | # js
            const { buildMatrix } = require('./.github/scripts/matrix-builder')

            const result = buildMatrix({
              chunks: Number(process.env.chunks),
              specs: "${{ inputs.specs }}",
              defaultOptions: {
                "java-version": 21,
                runner: "ubuntu-22.04",
                edition: "ee"
              }
            })

            core.setOutput("regularChunks", JSON.stringify(result.regularChunks))
            core.setOutput("config", JSON.stringify(result.matrix))
