name: E2E Cross-version Tests

on:
  workflow_dispatch:
    inputs:
      fe-ref:
        description: "Frontend git ref to use"
        type: string
        required: true
        default: "master"
      be-ref:
        description: "Backend git ref to use"
        type: string
        required: true
        default: "master"
  workflow_call:
    inputs:
      fe-ref:
        description: "Frontend git ref to use"
        type: string
        required: true
      be-ref:
        description: "Backend git ref to use"
        type: string
        required: true

jobs:
  cross-version-for-breaking-changes:
    runs-on: ubuntu-22.04
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build jar with different frontend and backend version
        run: |
          bash bin/embedding-sdk/backward-compatibility-test.sh \
            ${{ inputs.fe-ref }} ${{ inputs.be-ref }} \
            build

      - name: Prepare Cypress environment
        id: cypress-prep
        uses: ./.github/actions/prepare-cypress

      - name: Start the jar
        run: |
          bash bin/embedding-sdk/backward-compatibility-test.sh \
            ${{ inputs.fe-ref }} ${{ inputs.be-ref }} \
            run

      - name: Run the cypress tests
        run: |
          bash bin/embedding-sdk/backward-compatibility-test.sh \
            ${{ inputs.fe-ref }} ${{ inputs.be-ref }} \
            test
